[General]
; Input mode:
; siapi     - (Default) In this mode, a custom SIAPI SteamTouchPad control is used for camera control,
;             similar to Horizon Zero Dawn Remastered. Raw mouse input remains untouched and cannot be used
;             simultaneously with a controller. The advantage of this is that Photo Mode works more cleanly
;             and as the trackpad does not control the system cursor, the cursor cannot escape the game window
;             when it does not trap it.
; raw_mouse - (Legacy) In this mode, simultaneous raw mouse & controller input is enabled. This allows using
;             any mouse input together with controller input. The trackpad must be set to operate "As Mouse".
;             Try this mode if the other one doesn't work, or if you want to use a regular mouse together with
;             a controller.
mode = siapi

[Debug]
; Log level: debug, info, warn, error, off (default: info)
; Controls the verbosity of mixed_input_fix.log (set to 'off' to disable logging completely)
log_level = info
